apiVersion: apps/v1
kind: Development
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      spec:
        containers:
          - name: auth
            image: waysoning/auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: ClusterIP # default
  ports: 
    - name: auth
      protocal: TCP
      port: 3000
      targetPort: 3000